import { Router } from 'express';
import authRouter from './auth.routes';
import userRouter from './user.routes';
import vibeRouter from './vibe.routes';
import hobbyRouter from './hobby.routes';
import interestRouter from './interest.routes';
import networkConnectionRouter from './network-connection.routes';
import blockedUserRouter from './blocked-user.routes';
import eventCategoryRouter from './event-category.routes';
import feedRouter from './feed.routes';
import feedLikedRouter from './feed-liked.routes';
import feedSharedRouter from './feed-shared.routes';
import feedCommentRouter from './feed-comment.routes';
import feedReportRouter from './feed-report.routes';
import commentReportRouter from './comment-report.routes';
import commentLikeRouter from './comment-like.routes';
import reportReasonRouter from './report-reason.routes';
import eventRouter from './event.routes';
import mediaUploadRouter from './media-upload.routes';
import rsvpRequestRouter from './rsvp-request.routes';
import gamificationCategoryRouter from './gamification-category.routes';
import gamificationBadgeRouter from './gamification-badge.routes';
import gamificationDiamondRouter from './gamification-diamond.routes';
import userGamificationPointsRouter from './user-gamification-points.routes';
import userGamificationCategoryBadgesRouter from './user-gamification-category-badges.routes';
import stripeRouter from './stripe.routes';
import stripeProductRouter from './stripe-product.routes';
import chatRoomRouter from './chat-room.routes';
import messageRouter from './message.routes';
import transactionRouter from './transaction.routes';
import subscriptionRouter from './subscription.routes';
import notificationRouter from './notification.routes';
import eventAttendeesRouter from './event-attendees.routes';
import tagRouter from './tag.routes';
import segmentRouter from './segment.routes';
import customerRouter from './customer.routes';

const indexRouter = Router();

indexRouter.use('/auth', authRouter);
indexRouter.use('/users', userRouter);
indexRouter.use('/vibe', vibeRouter);
indexRouter.use('/hobbies', hobbyRouter);
indexRouter.use('/interests', interestRouter);
indexRouter.use('/network-connections', networkConnectionRouter);
indexRouter.use('/blocked-users', blockedUserRouter);
indexRouter.use('/event-categories', eventCategoryRouter);
indexRouter.use('/feeds', feedRouter);
indexRouter.use('/feed-likes', feedLikedRouter);
indexRouter.use('/feed-shares', feedSharedRouter);
indexRouter.use('/feed-comments', feedCommentRouter);
indexRouter.use('/feed-reports', feedReportRouter);
indexRouter.use('/comment-reports', commentReportRouter);
indexRouter.use('/comment-likes', commentLikeRouter);
indexRouter.use('/report-reasons', reportReasonRouter);
indexRouter.use('/events', eventRouter);
indexRouter.use('/media-upload', mediaUploadRouter);
indexRouter.use('/rsvp-requests', rsvpRequestRouter);
indexRouter.use('/gamification-categories', gamificationCategoryRouter);
indexRouter.use('/gamification-badges', gamificationBadgeRouter);
indexRouter.use('/gamification-diamonds', gamificationDiamondRouter);
indexRouter.use('/user-gamification-points', userGamificationPointsRouter);
indexRouter.use('/gamification', userGamificationCategoryBadgesRouter);
indexRouter.use('/stripe', stripeRouter);
indexRouter.use('/chat-rooms', chatRoomRouter);
indexRouter.use('/messages', messageRouter);
indexRouter.use('/transaction', transactionRouter);
indexRouter.use('/subscription', subscriptionRouter);
indexRouter.use('/subscription/plan', stripeProductRouter);
indexRouter.use('/event-attendees', eventAttendeesRouter);
indexRouter.use('/notifications', notificationRouter);
indexRouter.use('/tags', tagRouter);
indexRouter.use('/segments', segmentRouter);
indexRouter.use('/customers', customerRouter);
export default indexRouter;