export const responseMessages = {
    // Module: Vibes
    vibe: {
        retrieved: 'Vibes fetched successfully.',
        retrievedSingle: 'Vibe fetched successfully.',
        notFoundSingle: 'Vibe not found.',
        notFound: 'No vibes found.',
        failedToFetch: 'Failed to fetch all vibes.',
        failedToFetchSingle: 'Failed to fetch vibe.',
        alreadyExists: 'Vibe with this name already exists.',
        created: 'Vibe created successfully',
        failedToCreate: 'Failed to create vibe.',
        updated: 'Vibe updated successfully',
        failedToUpdate: 'Failed to update vibe.',
        deleted: 'Vibe deleted successfully',
        failedToDelete: 'Failed to delete vibe.',
    },
    // Module: Interests
    interest: {
        retrieved: 'Interests fetched successfully.',
        retrievedSingle: 'Interest fetched successfully.',
        notFoundSingle: 'Interest not found.',
        notFound: 'No interests found.',
        failedToFetch: 'Failed to fetch all interests.',
        failedToFetchSingle: 'Failed to fetch interest.',
        alreadyExists: 'Interest with this name already exists.',
        created: 'Interest created successfully',
        failedToCreate: 'Failed to create interest.',
        updated: 'Interest updated successfully',
        failedToUpdate: 'Failed to update interest.',
        deleted: 'Interest deleted successfully',
        failedToDelete: 'Failed to delete interest.',
    },
    // Module: Hobbies
    hobby: {
        retrieved: 'Hobbies fetched successfully.',
        retrievedSingle: 'Hobby fetched successfully.',
        notFoundSingle: 'Hobby not found.',
        notFound: 'No hobbies found.',
        failedToFetch: 'Failed to fetch all hobbies.',
        failedToFetchSingle: 'Failed to fetch hobby.',
        alreadyExists: 'Hobby with this name already exists.',
        created: 'Hobby created successfully',
        failedToCreate: 'Failed to create hobby.',
        updated: 'Hobby updated successfully',
        failedToUpdate: 'Failed to update hobby.',
        deleted: 'Hobby deleted successfully',
        failedToDelete: 'Failed to delete hobby.',
    },
    // Module: Event Categories
    eventCategory: {
        retrieved: 'Event categories fetched successfully.',
        retrievedSingle: 'Event category fetched successfully.',
        notFoundSingle: 'Event category not found.',
        notFound: 'No event categories found.',
        failedToFetch: 'Failed to fetch all event categories.',
        failedToFetchSingle: 'Failed to fetch event category.',
        alreadyExists: 'Event category with this name already exists.',
        created: 'Event category created successfully',
        failedToCreate: 'Failed to create event category.',
        updated: 'Event category updated successfully',
        failedToUpdate: 'Failed to update event category.',
        deleted: 'Event category deleted successfully',
        failedToDelete: 'Failed to delete event category.',
    },
    // Module: Report Reasons
    reportReason: {
        retrieved: 'Report reasons fetched successfully.',
        retrievedSingle: 'Report reason fetched successfully.',
        notFoundSingle: 'Report reason not found.',
        notFound: 'No report reasons found.',
        failedToFetch: 'Failed to fetch all report reasons.',
        failedToFetchSingle: 'Failed to fetch report reason.',
        alreadyExists: 'Report reason with this reason already exists.',
        created: 'Report reason created successfully',
        failedToCreate: 'Failed to create report reason.',
        updated: 'Report reason updated successfully',
        failedToUpdate: 'Failed to update report reason.',
        deleted: 'Report reason deleted successfully',
        failedToDelete: 'Failed to delete report reason.',
    },

    // Module: Authentication
    authentication: {
        socialLoginSuccess: 'Social login successful.',
        socialLoginFailed: 'Failed to login with social media.',
        loginSuccess: 'Login successful.',
        loginFailed: 'Failed to login.',
        registerSuccess: 'Register successful.',
        registerFailed: 'Failed to register.',
        forgotPasswordSuccess: 'Password reset successfully. Please check your email for the new password.',
        forgotPasswordFailed: 'Failed to forgot password.',
        resetPasswordSuccess: 'Password reset successfully.',
        resetPasswordFailed: 'Failed to reset password.',
        sendVerificationCodeSuccess: 'Verification code sent successfully.',
        sendVerificationCodeFailed: 'Failed to send verification code.',
        verifyCodeFailed: 'Failed to verify code.',
        invalidPassword: 'Invalid password.',
        invalidEmailOrPassword: 'Invalid email or password.',
        passwordNotSet: 'Password not set for your account. Please use "Forgot Password" to set your password.',
        accountDeleted: 'This account has been deleted.',
        invalidOrExpiredOTP: 'Invalid or expired OTP.',
        userNotFoundWithMobile: 'User not found with this mobile number.',
    },

    // Module: Media Upload
    mediaUpload: {
        uploaded: 'Media uploaded successfully.',
        failedToUpload: 'Failed to upload media.',
        noFileUploaded: 'No files found to upload. Please upload at least one file.',
    },

    // Module: User
    user: {
        tokenInvalid: 'Invalid or malformed token.',
        forbidden: 'Access denied. You do not have permission to perform this action.',
        retrieved: 'User fetched successfully.',
        retrievedSingle: 'User fetched successfully.',
        notFoundSingle: 'User not found.',
        notFound: 'No users found.',
        failedToFetch: 'Failed to fetch all users.',
        failedToFetchSingle: 'Failed to fetch user.',
        emailAlreadyRegistered: 'Email is already registered.',
        mobileAlreadyRegistered: 'Mobile number is already registered.',
        failedToCreate: 'Failed to create user.',
        updated: 'User updated successfully.',
        failedToUpdate: 'Failed to update user.',
        deleted: 'User deleted successfully.',
        failedToDelete: 'Failed to delete user.',
        userAlreadyDeleted: 'User is already deleted.',
        valueRequired: 'Value is required.',
        fcmTokensFormatRequired: 'Tokens must be provided as a comma-separated string.',
        fcmTokensRequired: 'At least one valid token must be provided.',
        fcmTokensUpdated: 'FCM tokens updated successfully',
        noNetworkUsers: 'No users found in your network.',
        networkBroadcastFailed: 'Failed to send network broadcast.',
        networkBroadcastSent: 'Network broadcast sent successfully.',
        invalidBroadcastType: 'Type must be either "email" or "sms".',
        broadcastOptionRequired: 'At least one of send_email or send_sms must be true.',
        profileSubscribed: 'Subscribed successfully.',
        profileUnsubscribed: 'Unsubscribed successfully.',
        cannotSubscribeToSelf: 'You cannot subscribe to yourself.',
    },

    // Module: Feed
    feed: {
        retrieved: 'Feeds fetched successfully.',
        retrievedSingle: 'Feed fetched successfully.',
        notFoundSingle: 'Feed not found.',
        notFound: 'No feeds found.',
        failedToFetch: 'Failed to fetch all feeds.',
        failedToFetchSingle: 'Failed to fetch feed.',
        created: 'Feed created successfully',
        failedToCreate: 'Failed to create feed.',
        updated: 'Feed updated successfully',
        failedToUpdate: 'Failed to update feed.',
        deleted: 'Feed deleted successfully',
        failedToDelete: 'Failed to delete feed.',
        forbidden: 'You do not have permission to perform this action.',
    },

    // Module: FeedLiked
    feedLiked: {
        liked: 'Feed liked successfully.',
        unliked: 'Feed like removed successfully.',
        alreadyLiked: 'Feed is already liked by the user.',
        notLiked: 'Feed is not liked by the user.',
        retrieved: 'Feed likes fetched successfully.',
        failedToFetch: 'Failed to fetch feed likes.',
        failedToFetchSingle: 'Failed to fetch feed like.',
        notFound: 'No likes found for the feed.',
        failedToCreate: 'Failed to toggle feed like.',
        failedToUpdate: 'Failed to update feed like.',
        failedToDelete: 'Failed to delete feed like.',
    },

    // Module: FeedShared
    feedShared: {
        feedShared: 'Feed shared successfully.',
        feedUnshared: 'Feed unshared successfully.',
        notShared: 'Feed is not shared with the specified peer.',
        retrieved: 'Feed shares fetched successfully.',
        notFound: 'No shares found for the feed.',
        failedToFetch: 'Failed to fetch feed shares.',
        failedToFetchSingle: 'Failed to fetch feed share.',
        cannotShareToSelf: 'Cannot share feed to yourself.',
        alreadyShared: 'Feed is already shared with the specified peer.',
        failedToShare: 'Failed to share feed.',
        failedToUnshare: 'Failed to unshare feed.',
        noUsersFoundInNetwork: 'No users found in your network.',
        peerIdRequired: 'Peer ID is required when send_entire_network is false.',
    },

    // Module: FeedReported
    feedReported: {
        reported: 'Feed reported successfully.',
        notFound: 'No reports found for the feed.',
        retrieved: 'Feed reports fetched successfully.',
        failedToFetch: 'Failed to fetch feed reports.',
        failedToFetchSingle: 'Failed to fetch feed report.',
        failedToCreate: 'Failed to report feed.',
        failedToUpdate: 'Failed to update feed report.',
        failedToDelete: 'Failed to delete feed report.',
        created: 'Feed report created successfully',
        updated: 'Feed report updated successfully',
        deleted: 'Feed report deleted successfully',
        forbidden: 'You do not have permission to perform this action.',
    },

    // Module: FeedCommented
    feedCommented: {
        commentAdded: 'Comment added to feed successfully.',
        replyAdded: 'Reply added to comment successfully.',
        commentDeleted: 'Comment deleted successfully.',
        commentUpdated: 'Comment updated successfully.',
        notFound: 'Comment not found.',
        retrieved: 'Feed comments fetched successfully.',
        failedToFetch: 'Failed to fetch feed comments.',
        failedToFetchSingle: 'Failed to fetch feed comment.',
        failedToCreate: 'Failed to add comment to feed.',
        failedToUpdate: 'Failed to update comment.',
        failedToDelete: 'Failed to delete comment.',
        parentCommentNotFound: 'Parent comment not found.',
        commentMismatch: 'Comment does not belong to this feed.',
        forbidden: 'You do not have permission to perform this action.',
    },

    // Module: CommentLiked
    commentLiked: {
        liked: 'Comment liked successfully.',
        unliked: 'Comment like removed successfully.',
        alreadyLiked: 'Comment is already liked by the user.',
        notLiked: 'Comment is not liked by the user.',
        retrieved: 'Comment likes fetched successfully.',
        failedToFetch: 'Failed to fetch comment likes.',
        failedToFetchSingle: 'Failed to fetch comment like.',
        notFound: 'No likes found for the comment.',
        failedToCreate: 'Failed to toggle comment like.',
        failedToUpdate: 'Failed to update comment like.',
        failedToDelete: 'Failed to delete comment like.',
    },

    // Module: CommentReported
    commentReported: {
        reported: 'Comment reported successfully.',
        notFound: 'No reports found for the comment.',
        retrieved: 'Comment reports fetched successfully.',
        failedToFetch: 'Failed to fetch comment reports.',
        failedToFetchSingle: 'Failed to fetch comment report.',
        failedToCreate: 'Failed to report comment.',
        failedToUpdate: 'Failed to update comment report.',
        failedToDelete: 'Failed to delete comment report.',
        created: 'Comment report created successfully',
        updated: 'Comment report updated successfully',
        deleted: 'Comment report deleted successfully',
        forbidden: 'You do not have permission to perform this action.',
    },

    // Module: Network Connection
    networkConnection: {
        connectionRequestCreated: 'Connection request created successfully.',
        failedToCreate: 'Failed to create network connection request.',
        failedToFetch: 'Failed to fetch all network connection requests.',
        retrieved: 'Network connection requests fetched successfully.',
        notFoundSingle: 'Network connection request not found.',
        notFound: 'Network connection request not found.',
        noRequestsFound: 'No network connection requests found.',
        cannotSendRequestToSelf: 'Cannot send connection request to yourself.',
        cannotSendRequestUserBlocked: 'Cannot send connection request. User is blocked.',
        connectionRequestExists: 'Connection request already exists.',
        requestAlreadySentByOtherUser: 'This user has already sent you a connection request.',
        usersAlreadyConnected: 'Users are already connected.',
        connectionRequestNotFound: 'Connection request not found.',
        canOnlyAcceptOwnRequests: 'You can only accept requests sent to you.',
        cannotAcceptRequestUserBlocked: 'Cannot accept request. User is blocked.',
        requestAlreadyAccepted: 'Request is already accepted.',
        cannotAcceptRejectedRequest: 'Cannot accept a rejected request.',
        connectionRequestAccepted: 'Connection request accepted successfully.',
        networkConnectionEstablished: 'Network connection established',
        canOnlyRejectOwnRequests: 'You can only reject requests sent to you.',
        cannotRejectRequestUserBlocked: 'Cannot reject request. User is blocked.',
        cannotRejectAcceptedRequest: 'Cannot reject an accepted request.',
        requestAlreadyRejected: 'Request is already rejected.',
        connectionRequestRejected: 'Connection request rejected successfully.',
        canOnlyDeleteOwnRequests: 'You can only delete your own requests.',
        connectionRequestDeleted: 'Connection request deleted successfully.',
        failedToAccept: 'Failed to accept connection request.',
        failedToReject: 'Failed to reject connection request.',
        failedToDelete: 'Failed to delete connection request.',
        connectionNotFound: 'Connection not found.',
        failedToRemove: 'Failed to remove connection.',
        cannotCancelRequest: 'Cannot cancel this request.',
        connectionRemoved: 'Connection removed successfully.',
        failedToCancel: 'Failed to cancel connection request.',
        connectionRequestCancelled: 'Connection request cancelled successfully.',
        cannotCancelReceivedRequest: 'Cannot cancel a request you received. You can only reject it.',
        myNetworkConnectionsRetrieved: 'My network connections fetched successfully.',
        myNetworkConnectionsNotFound: 'No network connections found.',
        failedToFetchMyNetworkConnections: 'Failed to fetch my network connections.',
        peopleYouMightKnowRetrieved: 'People you might know fetched successfully.',
        peopleYouMightKnowNotFound: 'No people you might know found.',
        failedToFetchPeopleYouMightKnow: 'Failed to fetch people you might know.',
    },

    // Module: Blocked User
    blockedUser: {
        cannotBlockSelf: 'Cannot block yourself.',
        userToBlockNotFound: 'User to block not found.',
        userAlreadyBlocked: 'User is already blocked.',
        userBlockedSuccess: 'User blocked successfully',
        userNotBlocked: 'User is not blocked.',
        userUnblockedSuccess: 'User unblocked successfully',
        failedToBlock: 'Failed to block user.',
        failedToUnblock: 'Failed to unblock user.',
        retrieved: 'Blocked users fetched successfully.',
        notFound: 'No blocked users found.',
        failedToFetch: 'Failed to fetch all blocked users.',
        failedToCheck: 'Failed to check if user is blocked.',
    },

    // Module: Event
    event: {
        failedToCreate: 'Failed to create event.',
        created: 'Event created successfully',
        updated: 'Event updated successfully',
        failedToUpdate: 'Failed to update event.',
        participantRoleUpserted: 'Event participant role updated successfully.',
        notFound: 'Event not found.',
        notFoundSingle: 'Event not found.',
        failedToFetch: 'Failed to fetch all events.',
        failedToFetchSingle: 'Failed to fetch event.',
        alreadyExists: 'Event with this name already exists.',
        failedToDelete: 'Failed to delete event.',
        deleted: 'Event deleted successfully',
        retrieved: 'Events fetched successfully.',
        retrievedSingle: 'Event fetched successfully.',
        deviceIDRequired: 'Device ID is required.',
        unliked: 'Event unliked successfully',
        liked: 'Event liked successfully',
        failedToCreateLike: 'Failed to create event like.',
        feedbackDataRequired: 'Feedback data is required.',
        feedbackSaved: 'Event feedback saved successfully',
        rsvpStatusRequired: 'RSVP status is required.',
        attendeeCreated: 'Event attendee created successfully',
        attendeeUpdated: 'Event attendee updated successfully',
        attendeeDeleted: 'Event attendee deleted successfully',
        attendeeNotFound: 'Event attendee not found.',
        failedToUpdateAttendee: 'Failed to update event attendee.',
        failedToDeleteAttendee: 'Failed to delete event attendee.',
        attendeeCheckedIn: 'Event attendee checked in successfully',
        attendeeUncheckedIn: 'Event attendee unchecked in successfully',
        failedToCheckInAttendee: 'Failed to check in event attendee.',
        failedToUncheckInAttendee: 'Failed to uncheck in event attendee.',
        previousAttendeesRetrieved: 'Previous event attendees retrieved successfully',
        notFoundPreviousAttendees: 'No previous event attendees found.',
        failedToFetchPreviousAttendees: 'Failed to fetch previous event attendees.',
        reported: 'Event reported successfully',
        viewCreated: 'Event view created successfully',
        onlyEventHostsCanViewRSVPRequests: 'Only event hosts can view RSVP requests.',
        noPendingRSVPRequests: 'No pending RSVP requests found.',
        rsvpRequestSent: 'RSVP request sent successfully',
        rsvpRequestNotNeeded: 'RSVP approval is not required for this event.',
        rsvpRequestAlreadyApproved: 'RSVP request already approved.',
        rsvpRequestAlreadyPending: 'RSVP request already pending.',
        rsvpRequestsRetrieved: 'RSVP requests retrieved successfully',
        rsvpRequestApproved: 'RSVP request approved successfully',
        rsvpRequestRejected: 'RSVP request rejected successfully',
        failedToSendRSVPRequest: 'Failed to send RSVP request',
        failedToFetchRSVPRequests: 'Failed to fetch RSVP requests',
        failedToProcessRSVPRequest: 'Failed to process RSVP request',
        noProcessedRSVPRequests: 'No processed RSVP requests found.',
        onlyEventHostsCanApproveRejectRSVPRequests: 'Only event hosts can approve/reject RSVP requests.',
    },

    // Module: Gamification Category
    gamificationCategory: {
        retrieved: 'Gamification categories fetched successfully.',
        retrievedSingle: 'Gamification category fetched successfully.',
        notFoundSingle: 'Gamification category not found.',
        notFound: 'No gamification categories found.',
        failedToFetch: 'Failed to fetch all gamification categories.',
        failedToFetchSingle: 'Failed to fetch gamification category.',
        alreadyExists: 'Gamification category with this name already exists.',
        created: 'Gamification category created successfully',
        failedToCreate: 'Failed to create gamification category.',
        updated: 'Gamification category updated successfully',
        failedToUpdate: 'Failed to update gamification category.',
        deleted: 'Gamification category deleted successfully',
        failedToDelete: 'Failed to delete gamification category.',
    },

    // Module: Gamification Badge
    gamificationBadge: {
        retrieved: 'Gamification badges fetched successfully.',
        retrievedSingle: 'Gamification badge fetched successfully.',
        notFoundSingle: 'Gamification badge not found.',
        notFound: 'No gamification badges found.',
        failedToFetch: 'Failed to fetch all gamification badges.',
        failedToFetchSingle: 'Failed to fetch gamification badge.',
        alreadyExists: 'Gamification badge with this event count already exists.',
        created: 'Gamification badge created successfully',
        failedToCreate: 'Failed to create gamification badge.',
        updated: 'Gamification badge updated successfully',
        failedToUpdate: 'Failed to update gamification badge.',
        deleted: 'Gamification badge deleted successfully',
        failedToDelete: 'Failed to delete gamification badge.',
    },

    // Module: Gamification Diamond
    gamificationDiamond: {
        retrieved: 'Gamification diamonds fetched successfully.',
        retrievedSingle: 'Gamification diamond fetched successfully.',
        notFoundSingle: 'Gamification diamond not found.',
        notFound: 'No gamification diamonds found.',
        failedToFetch: 'Failed to fetch all gamification diamonds.',
        failedToFetchSingle: 'Failed to fetch gamification diamond.',
        alreadyExists: 'Gamification diamond with this color already exists.',
        created: 'Gamification diamond created successfully',
        failedToCreate: 'Failed to create gamification diamond.',
        updated: 'Gamification diamond updated successfully',
        failedToUpdate: 'Failed to update gamification diamond.',
        deleted: 'Gamification diamond deleted successfully',
        failedToDelete: 'Failed to delete gamification diamond.',
    },

    // Module: User Gamification Points
    userGamificationPoints: {
        retrieved: 'User gamification points fetched successfully.',
        retrievedSingle: 'User gamification points fetched successfully.',
        notFoundSingle: 'User gamification points not found.',
        notFound: 'No user gamification points found.',
        failedToFetch: 'Failed to fetch user gamification points.',
        failedToFetchSingle: 'Failed to fetch user gamification points.',
        failedToFetchTotal: 'Failed to fetch total earned points.',
        totalPointsRetrieved: 'Total earned points fetched successfully.',
        created: 'User gamification points created successfully',
        failedToCreate: 'Failed to create user gamification points.',
        initialized: 'User gamification points initialized for all categories successfully.',
        failedToInitialize: 'Failed to initialize user gamification points.',
        updated: 'User gamification points updated successfully',
        failedToUpdate: 'Failed to update user gamification points.',
        deleted: 'User gamification points deleted successfully',
        failedToDelete: 'Failed to delete user gamification points.',
    },

    // Module: User Gamification Category Badges
    userGamificationCategoryBadge: {
        created: 'User gamification category badge created successfully',
        failedToCreate: 'Failed to create user gamification category badge.',
    },

    // Module: Stripe
    stripe: {
        emailRequired: 'User email is required for stripe account creation.',
        accountAlreadySetUp: 'Stripe express account already set up.',
        onboardingLinkCreated: 'Stripe onboarding link created successfully.',
        failedToCreateOrRefreshAccount: 'Failed to create or refresh Stripe account.',
        accountNotOnboarded: 'User does not have a Stripe account. Please complete Stripe onboarding first.',
        dashboardLinkCreated: 'Stripe dashboard login link created successfully.',
        failedToCreateDashboardLink: 'Failed to create Stripe dashboard login link.',
        productIdRequired: 'Product ID is required.',
        productNotFound: 'Product not found.',
        productNotFoundInDatabase: 'Product not found in database.',
        productNotFoundInStripe: 'Product not found in Stripe.',
        productPermissionDenied: 'You do not have permission to perform this action on this product.',
        productCreated: 'Stripe product created successfully.',
        productUpdated: 'Stripe product updated successfully.',
        productDeleted: 'Stripe product deleted successfully.',
        productRetrieved: 'Product retrieved successfully.',
        productsRetrieved: 'User products retrieved successfully.',
        noProductsFound: 'No products found.',
        userIdRequired: 'User ID is required.',
        userIdOrAuthRequired: 'User ID or authentication is required.',
        failedToCreateProduct: 'Failed to create stripe product.',
        failedToUpdateProduct: 'Failed to update stripe product.',
        failedToDeleteProduct: 'Failed to delete stripe product.',
        failedToGetProduct: 'Failed to get stripe product.',
        failedToGetUserProducts: 'Failed to get user stripe products.',
        accountNotActive: 'Stripe account is not active. Please complete Stripe onboarding first.',
        accountNotFullyOnboarded: 'Stripe account is not fully onboarded. Please complete Stripe onboarding first.',
        priceNotFound: 'Price not found.',
        subscriptionIntentCreated: 'Subscription payment intent created successfully.',
        failedToCreateSubscriptionIntent: 'Failed to create subscription payment intent.',
        subscriptionNotFound: 'Subscription not found.',
        subscriptionIdRequired: 'Subscription ID is required.',
        subscriptionCanceled: 'Subscription canceled successfully.',
        failedToCancelSubscription: 'Failed to cancel subscription.',
        subscriptionAlreadyCanceled: 'Subscription is already canceled.',
        paymentIntentCreated: 'Payment intent created successfully.',
        failedToCreatePaymentIntent: 'Failed to create payment intent.',
        paymentIntentUpdated: 'Payment intent updated successfully.',
        failedToUpdatePaymentIntent: 'Failed to update payment intent.',
        paymentIntentIdRequired: 'Stripe payment intent id is required.',
        totalLessThanSubtotal: 'Total cannot be less than subtotal.',
        eventNotFound: 'Event not found.',
        eventNoHost: 'Event does not have a host.',
        eventHostNotFound: 'Event host not found.',
        failedToGetSubscribers: 'Failed to get subscribers.',
        subscribersRetrieved: 'Subscribers retrieved successfully.',
    },
    transaction: {
        transactionNotFound: 'Transaction not found.',
        transactionIdRequired: 'Transaction ID is required.',
        failedToGetTransactions: 'Failed to get transactions.',
        transactionsRetrieved: 'Transactions retrieved successfully.',
        transactionRetrieved: 'Transaction retrieved successfully.',
    },
    subscription: {
        subscriptionNotFound: 'Subscription not found.',
        subscriptionIdRequired: 'Subscription ID is required.',
        failedToGetSubscriptions: 'Failed to get subscriptions.',
        subscriptionRetrieved: 'Subscription retrieved successfully.',
        subscriptionsRetrieved: 'Subscriptions retrieved successfully.',
        productsRetrieved: 'Platform products retrieved successfully.',
        failedToGetProducts: 'Failed to get platform products.',
        failedToGetSubscription: 'Failed to get subscription.',
        priceIdRequired: 'Price ID is required.',
        productIdRequired: 'Product ID is required.',
        productNotFound: 'Platform product not found.',
        productRetrieved: 'Platform product retrieved successfully.',
        failedToGetProduct: 'Failed to get platform product.',
        subscriptionCreated: 'Platform subscription created successfully.',
        failedToCreateSubscription: 'Failed to create platform subscription.',
        subscriptionCanceled: 'Platform subscription canceled successfully.',
        failedToCancelSubscription: 'Failed to cancel platform subscription.',
        subscriptionUpdated: 'Platform subscription updated successfully.',
        failedToUpdateSubscription: 'Failed to update platform subscription.',
        featureUsageRetrieved: 'Feature usage retrieved successfully.',
        failedToGetFeatureUsage: 'Failed to get feature usage.',
        invalidFeatureKey: 'Invalid feature key.',
        featureAccessChecked: 'Feature access checked successfully.',
        failedToCheckFeatureAccess: 'Failed to check feature access.',
        featureUsageIncremented: 'Feature usage incremented successfully.',
        failedToIncrementFeatureUsage: 'Failed to increment feature usage.',
        analyticsRetrieved: 'Subscription analytics retrieved successfully.',
        failedToGetAnalytics: 'Failed to get subscription analytics.',
        priceNotFound: 'Platform price not found.',
        canCancelOnlyOwnSubscriptions: 'You can only cancel your own subscriptions',
    },

    // Module: ChatRoom
    chatRoom: {
        created: 'Chat room created successfully.',
        updated: 'Chat room updated successfully.',
        deleted: 'Chat room deleted successfully.',
        retrieved: 'Chat room fetched successfully.',
        retrievedAll: 'Chat rooms fetched successfully.',
        notFound: 'Chat room not found.',
        notFoundAll: 'No chat rooms found.',
        failedToCreate: 'Failed to create chat room.',
        failedToUpdate: 'Failed to update chat room.',
        failedToDelete: 'Failed to delete chat room.',
        failedToFetch: 'Failed to fetch chat room.',
        alreadyExists: 'Chat room already exists.',
        userJoined: 'User joined the chat room successfully.',
        userAlreadyInRoom: 'User already in this group.',
        personalRoomCannotJoin: 'This is a personal room and you cannot join.',
        invalidUserIds: 'Invalid user IDs.',
        userIdRequired: 'User ID is required.',
        roomIdRequired: 'Room ID is required.',
        eventIdRequired: 'Event ID is required.',
        nameRequired: 'Name is required when creating a group chat.',
        atLeastTwoUsersRequired: 'At least two user IDs are required for group chats.',
        atLeastOneUserRequired: 'At least one user ID is required for event groups.',
        exactlyTwoUsersRequired: 'Personal chat requires exactly 2 users.',
        noEventParticipants: 'No participants or attendees found for this event.',
        invalidData: 'Invalid data.',
        broadcastRoomCreated: 'Broadcast room created.',
        broadcastRoomUpdated: 'Broadcast room updated.',
        userAlreadyDeleted: 'User already deleted from this chat room.',
        groupOnlyUpdateAllowed: "You can only change the group's name and profile photo.",
        unreadCountsRetrieved: 'Unread message counts for all rooms retrieved successfully.',
    },
    // Module: ChatMessage
    message: {
        created: 'Message posted successfully.',
        updated: 'Message updated successfully.',
        deleted: 'Message deleted successfully.',
        retrieved: 'Message fetched successfully.',
        retrievedAll: 'Messages fetched successfully.',
        notFound: 'Message not found.',
        notFoundAll: 'No messages found.',
        failedToCreate: 'Failed to post message.',
        failedToUpdate: 'Failed to update message.',
        failedToDelete: 'Failed to delete message.',
        failedToFetch: 'Failed to fetch message.',
        markedAsRead: 'Messages marked as read successfully.',
        reactionAdded: 'Reaction added successfully.',
        userIdRequired: 'User ID is required.',
        roomIdRequired: 'Room ID is required.',
        messageIdRequired: 'Message ID is required.',
        messageOrFileRequired: 'Either text message or a file is required.',
        unauthorized: 'You are not authorized to perform this action.',
        userNotInRoom: 'User not found in this room.',
        noUsersFoundInNetwork: 'No users found in network.',
        peerIdsRequired: 'Peer IDs are required and must be a non-empty array when send_entire_network is false.',
        noValidPeerIds: 'No valid peer IDs provided. Cannot send message to yourself.',
    },
    // Module: Notification
    notification: {
        notFound: 'No notifications found.',
        notFoundSingle: 'Notification not found.',
        invalidType: 'Invalid notification type.',
        failedToFetch: 'Failed to fetch notifications.',
        retrieved: 'Notifications fetched successfully.',
        notificationIdRequired: 'Notification ID is required.',
        markedAsRead: 'Notification marked as read successfully.',
        allMarkedAsRead: 'All notifications marked as read successfully.',
        failedToMarkAsRead: 'Failed to mark notification as read.',
        failedToMarkAllAsRead: 'Failed to mark all notifications as read.',
        unreadCountRetrieved: 'Unread notification count fetched successfully.',
        failedToFetchUnreadCount: 'Failed to fetch unread notification count.',
    },
    // Module: Segment
    segment: {
        retrieved: 'Segments fetched successfully.',
        retrievedSingle: 'Segment fetched successfully.',
        notFoundSingle: 'Segment not found.',
        notFound: 'No segments found.',
        failedToFetch: 'Failed to fetch segments.',
        created: 'Segment created successfully.',
        failedToCreate: 'Failed to create segment.',
        updated: 'Segment updated successfully.',
        failedToUpdate: 'Failed to update segment.',
        deleted: 'Segment deleted successfully.',
        failedToDelete: 'Failed to delete segment.',
    },
    // Module: Tag
    tag: {
        retrieved: 'Tags fetched successfully.',
        retrievedSingle: 'Tag fetched successfully.',
        notFoundSingle: 'Tag not found.',
        notFound: 'No tags found.',
        failedToFetch: 'Failed to fetch tags.',
        created: 'Tag created successfully.',
        failedToCreate: 'Failed to create tag.',
        updated: 'Tag updated successfully.',
        failedToUpdate: 'Failed to update tag.',
        deleted: 'Tag deleted successfully.',
        failedToDelete: 'Failed to delete tag.',
        systemTagNotEditable: 'System tag cannot be edited.',
        systemTagNotDeletable: 'System tag cannot be deleted.'
    },
    // Module: Customer
    customer: {
        retrieved: 'Customers fetched successfully.',
        retrievedSingle: 'Customer fetched successfully.',
        notFoundSingle: 'Customer not found.',
        notFound: 'No customers found.',
        failedToFetch: 'Failed to fetch customers.',
        created: 'Customer created successfully.',
        failedToCreate: 'Failed to create customer.',
        updated: 'Customer updated successfully.',
        failedToUpdate: 'Failed to update customer.',
        deleted: 'Customer deleted successfully.',
        failedToDelete: 'Failed to delete customer.',
    },
    email: {
        notFoundSingle: 'Email not found.',
        failedToSend: 'Failed to send email.',
        deleted: 'Email deleted successfully.',
        failedToFetch: 'Failed to fetch emails.',
        retrieved: 'Emails fetched successfully.',
        failedToDelete: 'Failed to delete email.',
        retrievedSingle: 'Email fetched successfully.',
        sent: 'Email queued for sending successfully.',
    },
    sms: {
        notFoundSingle: 'SMS not found.',
        failedToSend: 'Failed to send SMS.',
        deleted: 'SMS deleted successfully.',
        failedToFetch: 'Failed to fetch SMS.',
        retrieved: 'SMS fetched successfully.',
        failedToDelete: 'Failed to delete SMS.',
        retrievedSingle: 'SMS fetched successfully.',
        sent: 'SMS queued for sending successfully.',
        limitExceeded: 'SMS limit exceeded. Please upgrade your plan to send more messages.',
    },
}